name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Запуск каждый день в 4:00 утра по UTC что соответствует 7 утра по МСК
    - cron: '0 4 * * *'
  # ↓ ДОБАВЛЕНО: Ручной запуск workflow ↓
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      browser:
        description: 'Browser to run tests in'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - chromium
        - firefox
        - webkit
      test-type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - smoke
        - regression

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npx playwright test
      env:
        ENVIRONMENT: ${{ github.event.inputs.environment }}
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
